name: CI/CD Pipeline to build and push

on: 
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g. 1.0.0)'
        required: true

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN_REPO }}
    - name: Build and push Docker image
      run: |
           docker build . --tag ghcr.io/fzfr/devops-test:${{ github.event.inputs.release_version }}
           docker tag ghcr.io/fzfr/devops-test:${{ github.event.inputs.release_version }} ghcr.io/fzfr/devops-test:latest           
           docker push ghcr.io/fzfr/devops-test:${{ github.event.inputs.release_version }}
           docker push ghcr.io/fzfr/devops-test:latest