name: CI/CD Pipeline to build and push

on: 
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g. v1.0.0)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v3
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build Docker image
      run: |
        docker build -t testing/welcome:${{ github.event.inputs.release_version }} .
        docker tag testing/welcome:${{ github.event.inputs.release_version }} testing/welcome:latest
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}
    
    - name: Push Docker image
      run: |
        docker push testing/welcome:${{ github.event.inputs.release_version }}
        docker push testing/welcome:latest        